name: 'Deploy to Cloud Run from Source'

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/${{ secrets.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-oidc'

      - name: 'Deploy to Cloud Run'
        run: |
          gcloud run jobs deploy fantasy-football-chat-bot \
            --source . \
            --region us-east1
            --project ${{ secrets.PROJECT_ID }}

      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
